### ISSUE TITLE
Any hope of supporting distros that log sshd to journalctl?

### ISSUE THREAD

**Issue by Strykar** [Yaser-Amiri/netdata-ssh-module#6]
On Arch, `sshd` logs can be viewed with `journalctl _COMM=sshd` or `journalctl -fu sshd`; it does not log to `/var/log/auth.log` or `/var/log/secure`.

**Comment by Yaser-Amiri** [comment]
To be honest, I can't do it now, I'm a little busy.

**Comment by Strykar** [comment]
Thanks, if I could, I would've submitted a PR, closing.
