### ISSUE TITLE
Not seeing failed login attempts

### ISSUE THREAD

**Issue by modem7** [Yaser-Amiri/netdata-ssh-module#8]
Heya,

I'm trying the chart, but not currently getting any results. 

I've got a rather locked down bastion host, so without certain prerequisites, bad actors won't get as far as "Failed password".

This would be the same for any server that only allows certain users/groups to connect and/or publickey auth.

```
Mar  8 02:44:59 Bastion sshd[258838]: Connection from <sourceIP> port 17337 on <destIP> port <destport> rdomain ""
Mar  8 02:44:59 Bastion sshd[258838]: Invalid user testing from <sourceIP> port 17337
Mar  8 02:45:00 Bastion sshd[258840]: Connection from <sourceIP> port 17338 on <destIP> port <destport> rdomain ""
Mar  8 02:45:00 Bastion sshd[258840]: Invalid user testing from <sourceIP> port 17338
Mar  8 02:45:01 Bastion sshd[258833]: Connection closed by invalid user testing <sourceIP> port 17336 [preauth]
Mar  8 02:45:04 Bastion sshd[258838]: Connection closed by invalid user testing <sourceIP> port 17337 [preauth]
Mar  8 02:45:06 Bastion sshd[258840]: Connection closed by invalid user testing <sourceIP> port 17338 [preauth]
```

Currently running Ubuntu 22.04.2 LTS.

**Comment by Yaser-Amiri** [comment]
This plugin searchs for `Failed password for invalid {something} ssh` in the logs, it doesn't cover your case, you can change it though, [here](https://github.com/Yaser-Amiri/netdata-ssh-module/blob/47eda4b7679f427194d1ffb2383114276a0df43d/SSH.chart.py#L31) is the line which you have to change.  
This project is really old and to be honest I personally don't use it anymore and don't have any plan to add anything to it. But feel free to fork it!

Thanks

**Comment by modem7** [comment]
No worries, 

Thanks!

It might be worthwhile archiving this repo if there are no plans to do anything further with it.
